### ISSUE TITLE
Wrong setting of inner update times for SVRE on your comparison

### ISSUE THREAD

**Issue by JHL-HUST** [CHENBIN99/AdaEA#3]
We are the authors of SVRE. We have  found that you did not use the correct parameter seting for the inner update times of SVRE for your comparison.  
In our paper, we said that "For SVRE, we set the internal update frequency M to four times the number of ensemble models". When the number of ensemble models is 4, then 4 times 4 is 16.  Also, in Figure 3 of our paper, we have shown that 16 is the best parameter setting for the  inner update times. 
In the experiments of your paper, you choose 4 and said that this is following our default setting. This is not correct.

**Comment by CHENBIN99** [comment]
Thanks for your feedback. 

In our experiments, we used both CNNs and ViTs as our surrogate models. We tested the performance of SVRE when `m = 4`, `8` and `16`, and we found that m is not exactly proportional to the final result when the models are very different, sometimes it is the best for `m = 4`, and sometimes it is `8`, and the SVRE at `m = 16` on the contrary presents a certain decrease due to the results of several iterations.

Considering all, we chose `m = 4` as the parameter for the experiment, and the related results are shown in the additional material.

It could be the different models used that are leading to the difference in Trade-offs
